server:
  port: 8080

spring:
    http:
      multipart:
        enabled: true
        max-file-size: 3MB
        max-request-size: 3MB
    jmx:
        default-domain: gateway5
    mvc:
      static-path-pattern: /static/**
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        cache: false
        mode: HTML5
    datasource:
         #name: testdata
         #url: jdbc:mysql://127.0.0.1:3306/testdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
         #username: root
         #password: 123456
        #name: edc_wg_cmcc
        #url: jdbc:sqlserver://10.48.190.4:1433;DatabaseName=edc_wg_cmcc
        #username: sa
        #password: Wg_cmcc!23

#        name: jzxn_dw
#        url: jdbc:sqlserver://10.48.190.212:1433;DatabaseName=jzxn_dw
#        username: cxtd
#        password: Pass+_w0rd@

#        name: NEI
#        url: jdbc:sqlserver://10.48.190.206:1433;DatabaseName=NEI
#        username: sa
#        password: Wg_cmcc!@

        name: YGYDATA
        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=YGYDATA
        username: sa
        password: admin@123

        #name: JZXN_CMCC
        #url: jdbc:sqlserver://10.48.190.171:1433;DatabaseName=JZXN_CMCC
        #username: sa
        #password: Nsn_sj3Yd!Jf8

        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xngls.neiproj.entity
#pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
  #reasonable: true
 # supportMethodsArguments: true
#  params:
 #   count: countSql


  #数据库配置
  #10.48.190.4
  #spring.datasource.url=jdbc:sqlserver://10.48.190.4:1433;DatabaseName=edc_wg_cmcc
  #spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
  #spring.datasource.username=sa
  #spring.datasource.password=Wg_cmcc!23


#thymeleaf start


